import type { IconType } from "react-icons";
import { BsImageAlt, BsMoonStarsFill, BsSunFill } from "react-icons/bs";
import {
  FaAws,
  FaBloggerB,
  FaDiscord,
  FaGithub,
  FaGoogle,
  FaLinkedin,
  FaNodeJs,
  FaUserNinja,
  FaUserSecret,
  FaVuejs,
  FaXTwitter,
} from "react-icons/fa6";
import {
  HiArrowRight,
  HiArrowTopRightOnSquare,
  HiArrowUpRight,
  HiCalendarDays,
  HiCheck,
  HiCheckCircle,
  HiChevronDown,
  HiChevronLeft,
  HiChevronRight,
  HiChevronUp,
  HiClipboard,
  HiEnvelope,
  HiExclamationCircle,
  HiExclamationTriangle,
  HiHome,
  HiInformationCircle,
  HiMiniAcademicCap,
  HiMiniGlobeAsiaAustralia,
  HiMiniMagnifyingGlass,
  HiMiniMinus,
  HiMiniPlus,
  HiMiniQuestionMarkCircle,
  HiMiniXMark,
  HiOutlineArrowPath,
  HiOutlineDocument,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineLink,
} from "react-icons/hi2";
import { LuChevronsLeftRight, LuMaximize } from "react-icons/lu";
import {
  PiBookBookmarkDuotone,
  PiGridFourDuotone,
  PiRocketLaunchDuotone,
  PiSparkleDuotone,
  PiUserCircleDuotone,
} from "react-icons/pi";
import {
  SiAngular,
  SiBitbucket,
  SiCheckmk,
  SiDart,
  SiDocker,
  SiDotnet,
  SiExpress,
  SiFlutter,
  SiGit,
  SiGitlab,
  SiGo,
  SiGooglecloud,
  SiGraphql,
  SiInfluxdb,
  SiIobroker,
  SiIonic,
  SiJavascript,
  SiKeycloak,
  SiKubernetes,
  SiLaravel,
  SiMongodb,
  SiMysql,
  SiNestjs,
  SiNextdotjs,
  SiNodered,
  SiNuxtdotjs,
  SiPhp,
  SiPostgresql,
  SiPython,
  SiReact,
  SiRedis,
  SiSass,
  SiSecurityscorecard,
  SiSwift,
  SiTerraform,
  SiTypescript,
  SiZigbee,
} from "react-icons/si";
import { VscAzure } from "react-icons/vsc";

export let iconLibrary: Record<string, IconType> = {
  chevronUp: HiChevronUp,
  chevronDown: HiChevronDown,
  chevronRight: HiChevronRight,
  chevronLeft: HiChevronLeft,
  chevronsLeftRight: LuChevronsLeftRight,
  refresh: HiOutlineArrowPath,
  arrowUpRight: HiArrowUpRight,
  check: HiCheck,
  arrowRight: HiArrowRight,
  helpCircle: HiMiniQuestionMarkCircle,
  infoCircle: HiInformationCircle,
  warningTriangle: HiExclamationTriangle,
  errorCircle: HiExclamationCircle,
  checkCircle: HiCheckCircle,
  email: HiEnvelope,
  blog: FaBloggerB,
  globe: HiMiniGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  userNinja: FaUserNinja,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  close: HiMiniXMark,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: HiHome,
  academicCap: HiMiniAcademicCap,
  gallery: BsImageAlt,
  discord: FaDiscord,
  google: FaGoogle,
  github: FaGithub,
  minus: HiMiniMinus,
  plus: HiMiniPlus,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  linkedin: FaLinkedin,
  x: FaXTwitter,
  clipboard: HiClipboard,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  dark: BsMoonStarsFill,
  light: BsSunFill,
  document: HiOutlineDocument,
  search: HiMiniMagnifyingGlass,
  sparkle: PiSparkleDuotone,
  maximize: LuMaximize,
  rocket: PiRocketLaunchDuotone,

  // Tools
  nextjs: SiNextdotjs,
  nuxt: SiNuxtdotjs,
  angular: SiAngular,
  vanillaJs: SiJavascript,
  knockoutjs: SiJavascript,
  jquery: SiJavascript,
  scss: SiSass,
  nestjs: SiNestjs,
  express: SiExpress,
  graphql: SiGraphql,
  python: SiPython,
  golang: SiGo,
  laravel: SiLaravel,
  ".net": SiDotnet,
  ionic: SiIonic,
  reactNative: SiReact,
  flutter: SiFlutter,
  docker: SiDocker,
  kubernetes: SiKubernetes,
  terraform: SiTerraform,
  googleCloud: SiGooglecloud,
  git: SiGit,
  gitlab: SiGitlab,
  bitbucket: SiBitbucket,
  postgresql: SiPostgresql,
  mongodb: SiMongodb,
  redis: SiRedis,
  influxdb: SiInfluxdb,
  timescaledb: SiPostgresql,
  mysql: SiMysql,
  mqtt: SiNodered,
  scada: SiJavascript,
  iot: SiJavascript,
  networkSecurity: SiSecurityscorecard,
  serverless: SiGooglecloud,
  aws: FaAws,
  awsLambda: SiGooglecloud,
  Keycloak: SiKeycloak,
  Vuejs: FaVuejs,
  Azure: VscAzure,
  Zigbee: SiZigbee,
  NodeJs: FaNodeJs,
  CheckMK: SiCheckmk,
  ioBroker: SiIobroker,
  cyberSecurity: SiSecurityscorecard,
  userSecret: FaUserSecret,

  // Programmiersprachen
  javascript: SiJavascript,
  typescript: SiTypescript,
  go: SiGo,
  php: SiPhp,
  dart: SiDart,
  swift: SiSwift,
  sql: SiPostgresql,
  css: SiSass,
};

export function setIcons(newIcons: Partial<Record<string, IconType>>) {
  const filteredEntries = Object.entries(newIcons).filter(
    ([, val]) => val !== undefined
  ) as [string, IconType][];

  const filteredObject: Record<string, IconType> =
    Object.fromEntries(filteredEntries);

  iconLibrary = { ...iconLibrary, ...filteredObject };
}
